Create login page
CS3219-AY2223S1/cs3219-project-ay2223s1-g47 pull request #17
Opened 2022-09-04 05:45 UTC by tanyjnaaman

## Overview

Closes #4 closes #8.

Main aims were to create a login page and routing between login, home and signup. Specifically, if a user lands on `/` but is not logged in, we should redirect to `/login`. If he wants to sign up, they can go to `/login`, and upon sign up, we should redirect to `/login`. And finally, upon logging in, we should redirect to `/`. 

### Main changes and their rationale(s)

* Implemented a `LoginPage.tsx`

This is virtually identical to `SignUpPage.tsx` and has a lot of repeated code. I've since created a new issue to potentially refactor this with layout components. 

* Implemented `ProtectedRoutes` with redirects and access flags. See it in `App.tsx`.
* Implemented a set of user service API callers that interface with the user service. They currently return dummy data.

Pay specific attention to `/auth` - it is intended to call an endpoint in the user service backend for authentication of the cookies. Because we intend to use JWT without explicitly passing cookies to the frontend (use as `httpOnly`, which is more secure), the only way to authenticate with the cookies are just to ping the backend. See [this](https://medium.com/geekculture/how-to-use-context-api-and-jwt-to-maintain-user-sessions-eb5602e83a03) for more details. 

* Implemented a `UserContextProvider` and `UserContext`

By setting user context (username, user ID, logged-in-status, login functions + logout functions) to be global, we avoid prop drilling, and will be able to automatically persist user sessions. 

### Testing

Run the server with `npm start`. Go to `/`. You should be redirected to login. Go to `/signup` and try to sign up (there's also some input validation logic, so test that, too). You should be redirected to `/login` after. Then try logging in. You should be redirected to `/` after.

2022-09-11 09:26 UTC, cookiedan42 requested changes

2022-09-11 09:26 UTC, cookiedan42 commented on frontend/.gitignore
> +.env
committing .env files is a bad practice
especially if / when they might contain secrets or sensitive endpoints that you don't want exposed in the future
Also to force people who clone the repo to set .env rather than launch sth undesirable

2022-09-11 09:26 UTC, cookiedan42 commented on frontend/.gitignore
> +.env
consider modifying the .env.local instead

2022-09-11 13:29 UTC, cookiedan42 submitted a review, later dismissed
please change it still, but going to approve in advance coz small change and generally ok

2022-09-12 03:48 UTC, tanyjnaaman commented on frontend/.gitignore
> +.env
My bad - forgot to add it to `.gitignore`, will instead commit a `.env.sample`!

2022-09-12 03:55 UTC, cookiedan42 approved these changes
LGTM

2022-09-14 07:06 UTC, merged